### ISSUE TITLE
Rendering large NIfTI files

### ISSUE THREAD

**Issue by hsellik** [niivue/niivue#1047]
Rendering large NIfTI files is being done with better performance on [Papaya Viewer](https://rii-mango.github.io/Papaya/). Is there anything one can do to maximize performance for large files with Niivue?

The aim is to only open the slice view, no need for volume rendering as it is computationally expensive.

For example, one can load ~1GB file in Papya Viewer, but not in Niivue even when the 3D view is disabled in multiplanar mode with the new option introduced in #1024 .

I can provide an example file if necessary.

**Comment by hanayik** [comment]
@hsellik, could you please provide an example image that does not perform well? You can send a download link to taylor.hanayik at virdx.com

**Comment by neurolabusc** [comment]
@hsellik Since Papaya uses WebGL1 it is constrained to 2D textures. In contrast, WebGL2 allows 3D textures. For volumetric data, 3D textures provide huge efficiency benefits for 2D slices (e.g. sagittal, coronal, axial, oblique slices can all natively sample a single texture) as well as 3D rendering. However, 3D textures are inherently limited to 2Gb by the API (and potentially less on some devices). NiiVue uses 32-bits per voxel (RGBA). It is worth remembering that MRI data is SNR constrained, and for most modalities scales with field strength. Therefore, the 2Gb limit is not a reasonable limit for our this application. NiiVue focuses on the neuroimaging niche, and provides a highly optimized solution for this domain. We focus our resources on this domain and stay in our lane. I do think for applications where extremely high resolution data is used you should look at tile-based solutions like [neuroglancer](https://github.com/google/neuroglancer).

**Comment by hsellik** [comment]
My usage indeed is out of the niche.

Using it more for metrology purposes, where the NIfTI file is not very large. The medical niche tools keep popping up for this purpose and NiiVue does have good dev experience and documentation.

I'll try downsampling / looking at other web based tools. Neuroglancer seems interesting.

Thank you for the clarification!
