### ISSUE TITLE
add cylinder (straw) shader for 3D crosshair (copy MRIcroGL metal implementation)

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#108]

**Comment by neurolabusc** [comment]
Here is an [implementation in Metal](https://github.com/neurolabusc/Metal-Demos/blob/5ddd15005f7eb9a48620cf74ebd929dc11f83c73/mesh/mesh.pas#L615). This creates a triangulated mesh, so we can use the same shaders for all mesh based functions (e.g. similar to Surfice, FreeSurfer, SUMA, ConnectomeWorkbench) this includes [brain meshes, connectomes, tractography, etc.](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage).

The end caps are made up of `n` triangles where n is the number of sides. Each end cap triangle has a vertex at the center of axis. So that a 3-sided prism has an end cap of 3 triangles, and a hexagonal cylinder has an end cap of six triangles.  I first implemented this with n-2 triangles, e.g. a 3-sided prism can have a single triangle end cap. However, this approach did create some pole effects for the vertex normals. Adding two extra triangles (and one extra vertex) per end cap seems worth it.

@cdrake to generalize this solution I have used indexed triangles, rather than triangles or triangle strips. There is a [strong rationale for this](http://hacksoflife.blogspot.com/2010/01/to-strip-or-not-to-strip.html).


![crossbar](https://user-images.githubusercontent.com/8930807/134554492-0e56a9ba-11b3-42fb-bf37-a19f201fee30.png)
