### ISSUE TITLE
esthetic comment

### ISSUE THREAD

**Issue by francopestilli** [niivue/niivue#1088]
The niiVue graphs currently have a heavy-weight feeling. It would be much more elegant to have"
- thinner lines for plotted lines and axes. 
- eliminate the grid (generally the most elegant) or make the grid lines extremely think and color them using a gray color to blad more with the background.

**Comment by neurolabusc** [comment]
https://github.com/niivue/niivue/blob/b2286367c3be9b46cd5c68845a408b32668b882a/src/niivue/index.ts#L166C1-L183C1

type Graph = {
  LTWH: number[]
  plotLTWH?: number[]
  opacity: number
  vols: number[]
  autoSizeMultiplanar: boolean
  normalizeValues: boolean
  isRangeCalMinMax: boolean
  backColor?: number[]
  lineColor?: number[]
  textColor?: number[]
  lineThickness?: number
  lineAlpha?: number
  lines?: number[][]
  selectedColumn?: number
  lineRGB?: number[][]
}

Chris Rorden, PhD
Endowed Chair of Neuroimaging
Co-Director, McCausland Center for Brain Imaging
Department of Psychology
University of South Carolina
Columbia, SC 29208, USA
email ***@***.***
web www.mricro.com

**Comment by neurolabusc** [comment]
@francopestilli as seen in the [timeseries live demo](https://niivue.github.io/niivue/features/timeseries2.html) we are trying to scale to a broad range of screen sizes, from mobile phones to computers. The current style was based on feedback from the OpenNeuro team and others. If you think this could be improved, can you tune the parameters to something you feel is a better solution and we can get a consensus. Without more details, your comment is a bit underspecified.

I do wonder if one thing we could improve is to make [graph.lineThickness](https://github.com/niivue/niivue/blob/b2286367c3be9b46cd5c68845a408b32668b882a/src/niivue/index.ts#L9514) dependent on the graph size, so rather than always 4 pixels, it becomes thinner or thicker depending on the resolution of the graph (in pixels). At the moment, this is a constant, which means that lines become relatively thicker on lower resolutions.
![small](https://github.com/user-attachments/assets/b5365990-3406-4f46-8a82-5ffbdf172f14)

![large](https://github.com/user-attachments/assets/b9adc0a5-20db-49df-b1cb-15dd164ecb42)

**Comment by neurolabusc** [comment]
@francopestilli why don't you try out the latest commit to branch `issue1086`. The line size is now dynamic. It might help for more explicit descriptions for other changes
![small](https://github.com/user-attachments/assets/fa475836-fe63-40be-9a1f-fe6fc4b626b4)
![big](https://github.com/user-attachments/assets/7e01a618-09c7-40b1-a2af-3bc8a9bed9c9)
