### ISSUE TITLE
niiview remote deploy

### ISSUE THREAD

**Issue by vikashg** [niivue/niivue#1093]
Hi I am trying to run niiview and host it remotely on a computer.. When I execute 
`npm run dev -- --host`
I get a blank page and the following output on the terminal. 
```
  VITE v5.3.4  ready in 190 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://x.x.x.x:5173/
  ➜  Network: http://x.x.x.x:5173/
  ➜  Network: http://x.x.x.x:5173/
  ➜  press h + enter to show help
```
I am not really sure what I can do to fix this. Can someone please advice. 
Thanks

**Comment by hanayik** [comment]
@vikashg , this can happen if some other process is already running on that port (perhaps another `vite` server, or something else?). To solve this, you can supply a port number in addition to the `--host` option:

Example: `npm run dev -- --host --port 8888`

**Comment by vikashg** [comment]
Hi @hanayik So, I resolved this. I think the problem that was happening was that I was within the institutions network. Once I was home it was working fine. Maybe adding this to documentation would be a good idea so that people are aware of the VPN based issues. 

Another maybe related question I had was that, is it possible to deploy niiview on a remote computer (like an Amazon EC2 instance) and use the public IP to view the images on my own desktop. In this case the images as well as the niiview will be on the EC2 instance itself.

**Comment by hanayik** [comment]
@vikashg:
- **Network**: VPN and institutional issues can be frustrating, but they are separate from the Niivue project. You would likely have similar problems if you tried to run any `vite` dev server with the `--host` option from another open source project or even other web apps or docker containers specifying `0.0.0.0` as the host given your institution's strict network setup. Glad you got it working in the end 😊.
- **Deploy / Hosting**: Niivue is a Javascript library, and it can be imported into any web application that runs in the browser. It is not meant to be hosted or deployed using the development utilities. The html pages and images in the Niivue repository are purely for demonstration purposes so that we can have minimal online demos. They are not intended to be full featured web applications. You are welcome to copy them and modify them if you think one would be a good starting point for your Niivue-powered application. I would not recommend running `npm run dev` on your AWS machine and using that as the main server though. It would probably work well for low traffic sites or just for your own lab/personal use, but would not be sufficient as a production solution. Instead, it would be better to develop your web app that uses Niivue in some way (maybe starting from a demo), and then build a static site and serve the site with `nginx` in a docker container (just one possible method). Even the Niivue demos hosted on GitHub pages do not use the development server via `npm run dev`. The static pages are built, and hosted using GitHub's static site server infrastructure. Hope this helps!

**Comment by vikashg** [comment]
Thanks @hanayik
