### ISSUE TITLE
port nifti_dog from niimath to nvmath

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#123]

**Comment by hanayik** [comment]
related to: https://github.com/niivue/niivue/issues/78

**Comment by neurolabusc** [comment]
When applying a Gaussian blur, one must choose an arbitrary [kernel radius](https://dsp.stackexchange.com/questions/10057/gaussian-blur-standard-deviation-radius-and-kernel-size) that trades off speed versus precision: in theory the tails of the Gaussian distribution are infinitely long, but within a few standard deviations the contribution of voxels is negligible. 

Different tools provide different cut off thresholds, for example [SPM](https://github.com/spm/spm12/blob/3085dac00ac804adb190a7e82c6ef11866c8af02/spm_smooth.m#L97) and FSL  retain high precision `round(6 * sigma)`, [OpenCV](https://github.com/opencv/opencv/blob/9c23f2f1a682faa9f0b2c2223a857c7d93ba65a6/modules/imgproc/src/smooth.cpp#L3782) uses `round(3 * sigma)` for UINT8 data and `round(4 * sigma)` for other datatypes, [AFNI](https://github.com/afni/afni/blob/25e77d564f2c67ff480fa99a7b8e48ec2d9a89fc/src/edt_blur.c#L1391) uses `ceil(2.5 * sigma)`, and [bioimagesuite](https://github.com/bioimagesuiteweb/bisweb/blob/210d678c92fd404287fe5766136379ec94750eb2/js/utilities/bis_imagesmoothreslice.js#L133) uses `floor(1.5 * sigma)`. 

I [updated niimath to for faster DoG](https://github.com/rordenlab/niimath/blob/cb71bc21aeaaecc2288d595ce4bf11e98d18df75/src/core32.c#L657) by using the AFNI cutoff instead of the FSL one. This seems more than sufficient seeing we will end up with a binary image (e.g. we will not retain precision). I realize that JavaScript is somewhat slow, so the code allows you to choose a cutoff such that `kKernelWid = 2.5` will apply the AFNI `ceil(2.5*sigma)`, whereas `kKernelWid = -6.0` will apply the FSL/SPM `round(6.0*sigma)` (e..g. the choice of negative or positive sign selects between the ceil and round).
