### ISSUE TITLE
Goal: become the default image viewer for openneuro.org

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#134]

**Comment by neurolabusc** [comment]
[Papaya](https://github.com/rii-mango/Papaya) is an outstanding pure JavaScript viewer. I would see them as filling a different niche rather than direct competitors. They use WebGL 1, which allows them to support legacy browsers but limits them to surface rendering. Thanks to their permissive licensing, we should leverage the outstanding DICOM and GIFTI support they have developed: 

 - [GIFTI](https://github.com/rii-mango/GIFTI-Reader-JS) meshes
 - [Daikon](https://github.com/rii-mango/Daikon) DICOM import.
