### ISSUE TITLE
switch to typescript

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#141]
NiiVue is growing in size (lines of code) and in complexity as we add new features. Using typescript during development can help ensure that we always remain consistent in our variable types we use as input parameters to functions and also ensure consistent return values. 

https://www.typescriptlang.org/

I particularly like the tuple type checking that we could use for lots of arrays in NiiVue code

https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types

**Comment by neurolabusc** [comment]
Since my training is in strongly typed computer languages, I would be a proponent. I do think with larger projects and multiple developers, static types or type hints help with the maintenance of code. 

However, I think @cdrake has the most extensive experience with larger projects, and I defer to his wisdom on this topic.

Will this impose limitations on our project: are there some environments that would support classic JavaScript but not type script?
