### ISSUE TITLE
The current main branch doesn't let me import

### ISSUE THREAD

**Issue by soichih** [niivue/niivue#167]
I am probably doing something wrong, but I've `npm link`-ed the current main branch with our application so I can try the latest code (that comes with `attachToCanvas` function). 

When I try to import it, I ran into the following error message.

```
// @ts-ignore
import { Niivue } from '@niivue/niivue'
```

> Uncaught SyntaxError: The requested module '/@fs/home/hayashis/syncthing/git/niivue/dist/niivue.js?t=1636749305097' does not provide an export named 'Niivue'

Is `Niivue` not the name for the default export anymore? I am not all that familiar with ES6 module so maybe I need to adjust something on my end.. but I just wanted to ask this here.

**Comment by hanayik** [comment]
@soichih, I'm looking into this. I'm going to update the distribution packaging to resolve this, and hopefully a few other issues. Once that is done I can then push to npm so that the latest NiiVue package can be installed normally.

**Comment by hanayik** [comment]
@soichih , this should be resolved by #171. When that is merged in (after review), I will update the npm package to the latest version. Which module bundler do you use BTW? I have tested the recent packaging changes with vite (now the default in niivue) and in Webpack, via cue-cli.

**Comment by soichih** [comment]
Great! Thank you very much! We use vite.

**Comment by hanayik** [comment]
@soichi, The latest npm published version of Niivue should now resolve this. Let me know if you have issues. I have updated a lot related to bundling. I have also updated the test suite so that things run MUCH faster locally.

From: Soichi Hayashi ***@***.***>
Date: Monday, 22 November 2021 at 3:55 pm
To: niivue/niivue ***@***.***>
Cc: Taylor Hanayik ***@***.***>, Assign ***@***.***>
Subject: Re: [niivue/niivue] The current main branch doesn't let me import (Issue #167)

Great! Thank you very much! We use vite.
