### ISSUE TITLE
Real-Time interaction

### ISSUE THREAD

**Issue by rogiedodgie** [niivue/niivue#175]
Since one of the goals of NiiVue is to support/enable/ease worldwide collaboration, it may be nice to be able to quickly communicate, both with respect to what you are looking, but also potentially visually/verbally, with someone somewhere else via the click of a button (or typing in a common keyword and then hitting a button). 
We (Anthony and I) were thinking that it would be ideal to have an option for real-time communication (something like WebRTC) but that voice or chat functionality would suffice. Something very basic of course, and as lightweight as possible.

**Comment by hanayik** [comment]
@rogiedodgie, this is definitely an interesting idea. @neurolabusc and I had previously discussed the idea of real-time interaction in the form of shared crosshairs/canvas display if two remote users wanted to browse the same data simultaneously. One user would be the driver, and the other would be the observer. We haven't expanded the idea much though. It would be nice for some teaching purposes, etc. That use case would require a central server to broker messages.

Adding that functionality in should be done in a minimal way such that the mechanisms to send and receive data are available in NiiVue. Probably JSON messages passed back and forth. 

However, I don't think NiiVue is the right place to add in WebRTC video/audio/chat abilities. I see those features as part of a larger application that included NiiVue. I imagine that you could have some website such as "share-my-nifti-images.com" that had the WebRTC functionality, and built onto NiiVue in order to allow some form of collaboration. NiiVue already has a "sync" feature that allows one canvas to drive another. That could be expanded to accept input from a WebRTC data channel in order to have two remote canvases interact. 

Even with WebRTC data channels (no audio or video) I think you'd need a central server hosted somewhere to handle initiating the P2P connection right? I don't know much about webRTC other than some quick googling to be honest.

**Comment by hanayik** [comment]
@rogiedodgie , What I meant by a larger application that included NiiVue wasn't Zoom, Teams, etc., but rather a separate neuoimaging desktop app that built on Niivue, rather than complicating NiiVue itself by adding webRTC related code. I do think it's an fun and interesting idea. I was only trying to minimize the complexity of NiiVue. I was thinking that two remote canvases could share data and be driven by webRTC messages without adding much code to Niivue itself.

**Comment by rogiedodgie** [comment]
I understand. I am thinking like a neuroscientist with a partner in a far off country that I need to collaborate with on a project, e.g. maybe they are teaching me the Fazekas Scale, maybe lesion drawing, maybe deciding what threshold to use on our fMRI data. Trying to emulate situation where you are talking with a colleague in the office, right?  Any communication ability is good, I like your idea of webRTC messages as that would be lightweight. It is possible someone could build a separate NiiVue app that includes this of course. I assume anybody building a NiiVue app will choose what parts to include, i.e. customize it. This would just be another possible part...
