### ISSUE TITLE
 -> ' -inv  generated a fatal error:  1

### ISSUE THREAD

**Issue by dazzag24** [niivue/niivue#206]
Hi,

I gave the feature-c-wasm branch as spin.

The `http://127.0.0.1:8080/features/niimath.invert.html` demo doesn't work.  Console log has this error:

```
<snip>
WebGL warning: drawArraysInstanced: Tex image TEXTURE_3D level 5 is incurring lazy initialization.
WebGL warning: drawArraysInstanced: Tex image TEXTURE_3D level 0 is incurring lazy initialization.
command is -inv niivue.umd.js:541:324597
Uint8Array(5) [ 45, 105, 110, 118, 0 ]
niivue.umd.js:541:324991
ptr is niivue.umd.js:541:325129
5308936 niivue.umd.js:541:325152
cimg length 11393280 niivue.umd.js:541:325310
img not all zeros niivue.umd.js:541:325443
img length 11393280 niivue.umd.js:541:325494
 -> ' -inv  generated a fatal error:  1
```

I'm running the code on WSLv2 with
```
$ node -v                                                                          
v17.2.0
```

Browser is Firefox 94.0.2 (64-bit) on WIndows 10

**Comment by hanayik** [comment]
Hi @dazzag24 , the invert demo is likely a bit dated now since there have been some wasm changes. We can update that (or remove it since the niimath command demo can do everything). The wasm branch is being actively developed now. It's close, and the niimath.command.html demo should work ok, but it would be great if you can test that on windows.

some issues blocking the #204 PR are:
- Niivue with wasm not working on Safari 15.1
- Niivue with wasm not working on iOS 15.1 

We are nearing completion on those though. Stay tuned. 
BTW, the niimath demo input element can accept nearly any fslmaths style command to run mathematical operations on the input image, and the flags can be chained just like you would with fslmaths

**Comment by neurolabusc** [comment]
@cdrake you should remove the `invert` demo. This is actually not a niimath/fslmaths function. I initially wrote the WASM example with the idea that the change would be easy to visualize but it would not require the user to change the contrast or brightness. In contrast, the regardless of the image intensity range of input a function like `dog` will always generate binary (0 or 1) images as output.

**Comment by cdrake** [comment]
This has already been removed.

**Comment by cdrake** [comment]
@dazzag24 if you pull this branch, this demo has been removed.  It was used to develop our loading WASM feature. The original WASM was a test WASM @neurolabusc  wrote which supported the -inv command.

**Comment by dazzag24** [comment]
Hi,

I can confirm that the niimath.command.html works on Firefox on Windows.

Thanks
