### ISSUE TITLE
Error in "quasar dev" related to wasm and webpack 5

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue#214]
I have the following error message in a quasar project, and can't use niivue. 

```
Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
For files that transpile to WebAssembly, make sure to set the module type in the 'module.rules' section of the config (e. g. 'type: "webassembly/async"').
(Source code omitted for this binary file)
```

**Comment by hanayik** [comment]
Hi @vincenzoml, I have just made some changes to niivue, try updating to the latest version. However, with webpack, you may need to enable the experimental features outlined here for WebAssembly: https://webpack.js.org/configuration/experiments/

Niivue uses Vite, and Vite handles the wasm without issue. I see that there is a Vite plugin for quasar, so it might be worth a look if you are not absolutely dependent on webpack https://quasar.dev/start/vite-plugin

**Comment by hanayik** [comment]
Also, we are actively working to make the WASM integration slightly better in NiiVue. We're going to separate the WASM functionality into a separate package.

**Comment by hanayik** [comment]
one more thought, you could try rolling back to a non-wasm version of niivue just to get things working in your project. `npm i @niivue/niivue@0.12.4`

**Comment by vincenzoml** [comment]
Hi, quasar does not advice (yet?) to use vite, as quasar-cli fully supports only webpack, so I'd rather stay with webpack. But the latest changes made niivue work again with webpack so I'm happy!

**Comment by vincenzoml** [comment]
Reopening: I had mistakenly typed "yarn add @niivue/niivue@latest in the main project directory and not in the sources directory. The latest version does **not** fix the issue for me.

**Comment by hanayik** [comment]
Hi, @vincenzoml did you try the non-wasm version of NiiVue that I mentioned above? That would be a good test for us.

**Comment by vincenzoml** [comment]
Oh, sorry I forgot to mention: yes I'm now using 0.12.4, it works fine. Would be great to get the latest version without wasm (but is wasm meant to make it even faster? If so I'm also interested in that, since I'm using niivue for showing datasets, not just single images).

**Comment by hanayik** [comment]
Ok, good to know that the pre-wasm version works fine for you. Thanks for testing that.

The wasm parts of NiiVue don't make it faster for simple cases like loading and displaying images. The wasm part is intended to be used when users want to perform voxelwise calculations that might otherwise be slow in JavaScript. We have compiled niimath (a C clone of fslmaths) so that users can use an fslmaths-like command string to run computations.

It's documented more in the niimath repo here:

https://github.com/rordenlab/niimath/blob/development/src/JavaScript.md

The wasm component of NiiVue is very new, so we're actively working on it.
________________________________

**Comment by vincenzoml** [comment]
Thanks for the clarification! Related to this, did you consider also itk.js?


V.

**Comment by hanayik** [comment]
We did consider itk.js (#99 ) a few months ago. However since then @cdrake has made a couple of PRs to the nifti-reader-js repo to add the functionality we wanted. At that time, I don't think itk-wasm was published on GitHub (if it was I didn't know about it then). That project looks interesting, and does share some similarities with our C wasm web worker method.

**Comment by hanayik** [comment]
Hi @vincenzoml, I have just modified the wasm web worker import slightly. I'm curious if niivue 0.15.1 will work for you? Mind testing? You can always revert back to the non-wasm version of niivue you are using now.

**Comment by hanayik** [comment]
@vincenzoml , I have just published version 0.16.0 with wasm removed (I was having issues importing niivue with wasm in other projects too). Our niimath wasm has been moved to a development branch and will be integrated at a later date.

**Comment by vincenzoml** [comment]
Hi, version 0.16.0 works fine here, thanks for fixing this.

Sorry for polluting the issue tracker: I do have several questions but can't find either a forum or a chat. I'm implementing the UI for voxlogica (see https://github.com/vincenzoml/VoxLogicA) but there are things I don't know how to do. How can I get in touch?

**Comment by hanayik** [comment]
@vincenzoml, you can use the NiiVue issue tracker. Feel free to just start a new issue. We use it as our general todo list for NiiVue. There's no need for a forum, or chat app.

**Comment by vincenzoml** [comment]
Amazing, thanks! Will do that.
