### ISSUE TITLE
Included NiiVue in the VIZBI 2022 WebGL Masterclass

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#288]
Hi Everyone,

I love NiiVue because of the extremely fast rendering and great volume rendering functionality.

The other day, I gave a masterclass on WebGL at VIZBI https://vizbi.org/2022/Masterclass/ and I included NiiVue as part of a hands-on exercise to develop a drag'n'drop NII viewer. Here is the code we used https://github.com/haehn/VIZBI/blob/main/niivue.html

Great job again!
Daniel

**Comment by neurolabusc** [comment]
@haehn thanks for the kind words. I notice that you both contribute to and use [XTK](https://github.com/xtk) for your class. The open source license of XTK will allow us to bring a lot of those ideas to WebGL, similar to how we have leveraged the seminal work of [Papaya](https://github.com/rii-mango/Papaya).

Please contact us if you have the time and interest to join us. Even if your time commitment is low, your areas of expertise would be a terrific help.

Looking at your class, a few things strike me:
 1. We have just added mesh support (GIfTI, MZ3, OBJ) and we should add legacy VTK to the supported formats.
 2. While we have been focused on NIfTI for voxels, I really like the elegant NRRD format, and we should add support for this soon.
 3. For tractography, support for TRK/TCK is planned. With your help we could consider [TRAKO](https://github.com/bostongfx/TRAKO/) as well as [TRX](https://github.com/frheault/tractography_file_format). Since high-DPI displays are becoming popular and WebGL lines are limited to [1 pixel](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/lineWidth) we will implement [imposters](https://www.springerprofessional.de/en/a-simple-and-efficient-cylinder-imposter-approach-to-visualize-d/14979844) similar to [Surfice](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage).
 4. Our collaboration can be reciprocal. In the same way we can use proven XTK code (with attribution) you can leverage some of the NiiVue ideas. For example, if you are interested in using WASM, you might like our [voxel to mesh conversion](https://rordenlab.github.io/nii2meshWeb/) or our image processing (e.g. dehazing and edge finding for voxelwise data).

**Comment by hanayik** [comment]
as @neurolabusc said, thanks for the kind words @haehn. We would be happy to have you contribute code/ideas/suggestions/fun demos to NiiVue anytime!

I'm actively incorporating NiiVue into the new FSL user interfaces as well. Here's a fun sneak-peek at what that looks like:

<img width="1112" alt="Screenshot 2022-03-22 at 2 46 45 pm" src="https://user-images.githubusercontent.com/5217720/159509847-3737a886-b463-4e29-bda5-0125bb7d05ca.png">

**Comment by hanayik** [comment]
@haehn, I did want to point out that there's a risk the niivue src link you are using could break. That [link you have used ](https://github.com/haehn/VIZBI/blob/59faf9ad6d8df8a4847574b6aeba1f14b25cc032/niivue.html#L13) reflects the state of the main branch, and it could contain a bug from time to time, or it could change location if the demos structure is modified. 

It would be more stable to use the unpkg src URL. This has the added benefit of pinning a version. 

`<script src="https://unpkg.com/@niivue/niivue@0.22.3/dist/niivue.umd.js"></script>`
