### ISSUE TITLE
feature: modulate alpha component by another image value at each voxel location

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#335]

**Comment by neurolabusc** [comment]
@hanayik I think the standard approach is to modulate the voxel intensity of two images, not the alpha. In other words, the voxels of the target image darker or brighter based on the source image, not more or less translucent. The difference between modulating intensity and alpha would be stark for images with a white background.

Since JavaScript is slow, we would want to do this modulation on the GPU. Can we assume that the source and target image have a one-to-one correspondence of voxels (same number of rows, columns slices). I note that FSLeyes does not have this restriction, but we want to run with a much smaller RAM footprint than FSLeyes.

![modulate](https://user-images.githubusercontent.com/8930807/172371936-6688d0ba-e341-4345-a750-803bc3f6b358.png)
