### ISSUE TITLE
zooming in image space / viewport size

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#415]
Hi,

another question: zooming in world space somehow feels unnatural if the volume is not centered/aligned. Can we zoom in image space as well?

Also, we have 100% width and height for the container but it seems that niivue internally restricts the viewport inside the canvas. Can we modify this?

Thanks,
Daniel

**Comment by neurolabusc** [comment]
There are several methods for expanding an image. I personally like the FSLeyes method where the crosshair center stays at the same pixel location during expansion/contraction, so perhaps we should adopt that method. 

Tools like FSLeyes allow users to choose between voxel space and world space largely because the world space constrains the user. With FSLeyes the user is unable to edit drawings in the world space mode and voxels can exhibit aliasing artifacts that confuse users (see [here](https://github.com/rordenlab/dcm2niix/issues/627) and [here](https://github.com/rordenlab/dcm2niix/issues/595)). The image below shows this artifact in FSLeyes (top panel) and also the same image shown with NiiVue (bottom panel, with the lines on the rendering showing the sampling for the axial and coronal slices). Note that NiiVue's world space always samples from a single plane of voxels, avoiding aliasing artifacts, allowing drawing, and allowing one to simultaneously view meshes, connectomes and tractography streamlines. I believe this is a unique and powerful solution to this problem. Consider bing able to draw waypoints on a DWI scan in its native space, and interactively seeing how this constrains streamline way points. Rather than add features like panning and zooming to voxel space, my own vote would make the slice constrained world space the only view available in NiiVue. It resolves the age old dilemma between these two representations.

![eyes](https://user-images.githubusercontent.com/8930807/196543274-1a983c90-48f4-469f-8f83-c7be72073bf6.png)
![Vue](https://user-images.githubusercontent.com/8930807/196544517-fee5f301-9af4-41e0-8323-791e0ea1b72a.png)

**Comment by neurolabusc** [comment]
@cdrake offered to look at some of @haehn's feature suggestions. I am happy to help.
 - [cornerstone segmentation tools could be emulated](https://www.cornerstonejs.org/live-examples/basicsegmentationtools) including variable brush size (with shader to show brush diameter), 2D or 3D brush tools, and nice panning.
 - It would be great to improve the zoom of NiiVue world view so that the crosshair stays at a stable location (like FSLeyes).
 - It would be great to add zoom and pan to the NiiVue voxel view.
