### ISSUE TITLE
thresholding options:  transparent (or "alpha") thresholding, and boxing

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#435]
Standard thresholding does the following:  
+ Given a threshold value X, go to each voxel in the "threshold dataset" decide whether to display color there based on whether the voxel value is V>= X (hence, show the color) or V < X (hence, hide it away).  From an RGBA color schema, this means let the opacity channel be A=1 if the voxel value is V>=X, and let A=0 if it is V<X.

Consider instead the following for transparent (or "alpha") thresholding, sticking with the RGBA schema:
+ let A=1 if the voxel value is V>=X.
+ If V<X, instead of just flooring the opacity, consider making A = V/X, so that the value because more transparent linearly.  Or perhaps A = (V/X)**2, so the dropoff is quadratic.  That way, thresholding still applies, but visualization is less sensitive to the specific threshold (which is often semi-arbitrary and essentially a guide or reference).

For "boxing":
+ The transparency is useful, but to highlight where the boundary is, putting a "box" or line around the suprathreshold values might be useful.

This kind of functionality has been quite useful in AFNI.  It was described and promoted in:
+ Allen et al. (2012) https://www.sciencedirect.com/science/article/pii/S089662731200428X
+ Taylor et al. (2022) https://www.biorxiv.org/content/10.1101/2022.10.26.513929v2

**Comment by neurolabusc** [comment]
For the boxing, you can use [dFdx and dFdy](https://registry.khronos.org/OpenGL-Refpages/gl4/html/dFdx.xhtml) functions. [Here is a nice online demo](http://www.aclockworkberry.com/shader-derivative-functions/).

**Comment by neurolabusc** [comment]
@mrneont I have added experimental support for alpha thresholding that you can test out:

```
git clone --branch thresholding https://github.com/niivue/niivue.git
cd niivue
npm install
npm run dev
```

It might be worth having a Zoom meeting to discuss your vision and implementation details. Here is classic binary threshold:

![classic](https://user-images.githubusercontent.com/8930807/207872010-fccec8d4-e687-4dd6-98de-ac5e88dc5660.png)

And the same image with your suggested `A = (V/X)**` formula:

![alpha](https://user-images.githubusercontent.com/8930807/207872212-c00781cb-ed72-43a5-8f90-6f30c7e114f7.png)

Note that the colorbar in this mode shows an extended tick-mark at the statistical threshold. One issue is that the dynamic range for the colorbar gets diluted: in this example the red-yellow range spans z = 3..6 in the classic mode but must cover 0..6 in the alpha thresholding mode. So even though alpha blending is applied, the distinction of below and above threshold is hard to observe. This makes less extreme z-scores look much more salient than one might expect. Given that the false alarm rate grows non-linearly as Z approaches zero, I worry that we end up emphasizing noise. Since neuroimaging data is typically subjected to a Gaussian blur, it necessarily follows that statistically significant regions will be necessarily surrounded by near-threshold regions, so the opportunity for bloom seems extremely high.

I do like the idea of the boxing, but doing this efficiently on a screen-pixel (not image voxel) precision with a WebGL shader is harder than I imagined. The issue is that due to block alignment we do not know if dFdx() samples the neighbor to its left or its right. This is precisely the issue [described here](http://www.aclockworkberry.com/shader-derivative-functions/#Revealing_the_block_aligning_of_derivatives).  My commit includes commented out shader code that makes a box for precisely half the edges.  Effectively, the algorithm `I am an edge if I have Alpha of 1 and a non-zero derivative`  finds half the edges.

I did try one experimental solution to this problem. Here I use both alpha blending and removal of the green component to indicate that a voxel is sub-threshold. Since both the `warm` and `winter` are common in ramping green with intensity, this does highlight surviving voxels. However, this method seems very specific to the color schemes used. This discussion reminds me of the work by @CPernet on [brain_colours](https://github.com/CPernet/brain_colours) and the benefit of schemes that work with [colorblindness](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html).
![color](https://user-images.githubusercontent.com/8930807/207875939-733c0018-eb7a-4ba5-b781-925bb9e0028a.png).

**Comment by neurolabusc** [comment]
My latest version does use the shader to enable the outline box. With the `npm run dev` demo the box is controlled by the `Outline` checkbox that turns the line on (1) or off (0), though note in reality this is a numeric value so you could set other values, e.g. overlayOutlineWidth = 2.5. The one caveat is that this approach does not work well with trilinear interpolation, where the inherent smoothing means that the outline ends up being conservative. To see this, try selecting the `smooth` checkbox in the demo. I am open to suggestions on how to handle this.

![outline](https://user-images.githubusercontent.com/8930807/207960922-41a0931e-db59-428f-a2e4-f8dd3798145c.png)

**Comment by mrneont** [comment]
@neurolabusc : That looks (awesome)**2, given both the transparent thresholding and outlining.  I like the extended tick in the colorbar showing the location of the threshold value, too.

In general, I don't like smoothing the visualized data---I like the visualization when "smooth" is off (or what in AFNI would be applying NN interpolation within the image viewers, rather than linear, cubic, etc.).  It doesn't bother me to see pixelated data---that is what the datasets are.  So, this seems quite good, thanks! 

I will email you about chatting more, too.
