### ISSUE TITLE
Experimental SliceMM breaks syncWith

### ISSUE THREAD

**Issue by bwagnerwork** [niivue/niivue#440]
Hi NiiVue,
  I'm trying to create a online visualization of the CAT12 final report PDF which requires a slice level clip of the mesh which I would also like to link 2 other Vues.  I've been able to do this using some experimental feature(s).  However, I'm unable to link the view with any other views, even if all have setSliceMM (true).  Removing setSliceMM re-enables the sync.  But without setSliceMM I don't get the slice level clip.  Would you have any suggestions?  My code looks something like this...

```
this.nv = new Niivue();
this.nv.setRadiologicalConvention(true);
this.nv.setSliceType(this.nv.sliceTypeAxial);
this.nv.attachToCanvas(this.canvas.current);
this.nv.loadVolumes(volumeList);
this.nv.syncWith(this.props.syncWith.current.nv);
this.nv.loadMeshes(this.props.meshProps);
this.nv.setClipPlane([-0.1, 270, 0]);
this.nv.setRenderAzimuthElevation(120, 10);
this.nv.setMeshThicknessOn2D(0.75);
```

Ben

**Comment by neurolabusc** [comment]
@bwagnerwork I am having troubles replicating your issue. I started with the [sync mesh demo](https://niivue.github.io/niivue/features/sync.mesh.html) and it still works regardless of the setSliceMM setting. Maybe you can help us replicate your issue by starting with that demo. You can run `npm run demo` from the NiiVue root directory to test and modify that web page to illustrate your issue.

**Comment by bwagnerwork** [comment]
@neurolabusc I've created a simple example at: https://wagners.homeip.net/work/nv.html.  When loaded setSliceMM is off and the TOP canvas will control the other two*.  Toggling the "Slice MM" button will show the mesh, but then control of the other two are lost.  Toggling again restores control.  I've tried on Windows Chrome (107.0.5304.108) and Firefox 107.0.

*Not being able to sync all images from all images is another question for another time...

**Comment by bwagnerwork** [comment]
Ok, well this is interesting.  The sync break only happens on the single slice views. MultiPlanar and full 3D do sync.

**Comment by neurolabusc** [comment]
@bwagnerwork I am having trouble replicating your issue, but it might be because I am on a developmental branch. My first thought is that you are using an older version of NiiVue. Historically, meshes did not support slice views, but this has been extended. It is also possible to explicitly turn off 3D and 2D syncing, but in recent work both are enabled so the default without parameters is equivalent to:

```
nv1.syncWith(nv2, {'3d':true, '2d':true})
```

Regardless, would you mind trying out my developmental branch. I have updated the `Sync mesh` demo explicitly for your use case. I do not see any issues. If you could develop with this version, it should allow you to get familiar with the new features and provide feedback to me:

```
git clone --branch drawing https://github.com/niivue/niivue
cd niivue
npm install
npm run demo
```
![niivue](https://user-images.githubusercontent.com/8930807/205097444-20557cfd-b3e8-4d62-9799-0b50c47e2b4d.png)


This is a developmental branch. The known outstanding issues with this branch are all with `setSliceMM(false)`, and your use case is really for `nv2.setSliceMM(true)`.

**Comment by bwagnerwork** [comment]
@neurolabusc I'm seeing the same issue in the demo on drawing branch.  It shows when the view is any of the single planes.  It does not show in A+C+S+R or Render.  Maybe this clip will show what I'm seeing.  In multiplane you can see the top and bottom slices follow the crosshairs.  However in the single slice the top is independent.

https://user-images.githubusercontent.com/9351579/205111371-350cdc97-0f88-4a68-a9e9-7a27a73dbd08.mp4

I'm seeing the same effect on chrome, edge, firefox and vivaldi on windows.  Don't know if that is applicable.

**Comment by neurolabusc** [comment]
@bwagnerwork can you retest the drawing branch - my latest commit should resolve your issue.

**Comment by bwagnerwork** [comment]
@neurolabusc Issue is resolved.  Thanks!
