### ISSUE TITLE
custom interaction in 2D

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#464]
Hi!

I would like to change the interaction on the 2D slices as follows: 

mousewheel clicked -> pan
mousewheel scroll -> go through stack
right mouse button + up and down drag -> zoom

How can I do that? Compiling my custom NiiVue would be fine for me but I still struggle with identifying the callbacks that I need to switch.

**Comment by neurolabusc** [comment]
@haehn I have added handling of the center button to the `thresholding` branch, so you can try it out with:

```
git clone --branch thresholding git@github.com:niivue/niivue.git
cd niivue
npm install
npm run dev
```

Regardless of whether the drag mode is `contrast`, `measurement` or `pan`, dragging with the center button down will pan the image. This is not quite what you suggested, because tablets and phones do not have a center button, and for those we use the pinch gestures for zoom or slice scrolling. So my change does not change previous behavior, but adds new behavior. The new functions should make it easy for you to create a custom fork with your desired behavior.

Since the center button is only available on desktop implementations, you might want to try out my minimal [electron wrapper](https://github.com/niivue/afNiiVue). Web pages must live in a sandbox, so they have very limited use of the file system. This makes loading and saving files a bit cumbersome and the short-cut keys cumbersome. Using electron allows you to add shortcuts that make using a desktop-only platform more efficient for the user. The current electron app uses just the NiiVue core module, but in future we can have electron wrap [niivue-ui)](https://github.com/niivue/niivue-ui) for a much richer user experience.

**Comment by neurolabusc** [comment]
@haehn I have added a new feature to the development branch. With this branch, when you `npm run dev` the drop-down menu includes a new mode: `slicer3D`.  This will emulate Slicer3D's [3-button Rotate, Zoom, Pan](https://www.slicer.org/wiki/Documentation/4.1/SlicerApplication/MouseandKeyboardShortcuts) behavior. This will make the interaction familiar for users of this popular tool. In future, we could expand this mode to replicate the trackpad behavior.

**Comment by haehn** [comment]
Thank you - will try it!

**Comment by neurolabusc** [comment]
The `thresholding` development branch adds the [Slicer3D gesture](https://www.slicer.org/wiki/Documentation/4.1/SlicerApplication/MouseandKeyboardShortcuts) Shift+Left-Click & drag for panning to emulate slicer behavior for those with 1 and 2 button mice.

**Comment by haehn** [comment]
Thank you so much for the changes, @neurolabusc ! However, I noticed that scrolling with the mousewheel skips slices -  is this intended? If yes, could we please add a flag to not do that?
