### ISSUE TITLE
Drawing errors with nifti file

### ISSUE THREAD

**Issue by fib** [niivue/niivue#471]
Hi, this is a follow-up to the issue brought up in the last NiiVue meeting by @haehn.

We are having issues with the coordinates of our annotations as they appear to be flipped. We decided to test our nifti file in one of the demos for NiiVue but instead of mirrored coordinates the drawing didn't work at all. 

I have attached a video with a demonstration and the errors that were logged.

https://user-images.githubusercontent.com/47277578/211604579-7847199a-4bcd-4c48-9f2d-0f0d9ecb388d.mp4

**Comment by hanayik** [comment]
@fib, In this particular case, this looks like a result of not resetting the drawing bitmap to be an empty copy of the new background image. The drawing in this demo is retained from the brain example, but is not updated when you dropped a new file onto the canvas. I think if we just reset the drawing bitmap when a new background image is loaded that should solve this.

**Comment by neurolabusc** [comment]
The core issue is that you had a drawing open that matched the resolution of the background image. You then open a new background image with a different resolution without closing the open drawing.

@fib my latest commit on the `thresholding` branch now calls `closeDrawing()` when the user loads a new voxel based image. While this fixes the error you see, I think we want to decide if this is the default behavior. Note that if a user has been meticulously working on a drawing and then accidentally drops a image on the canvas they will destroy all their previous work! Our demo applications are meant to illustrate the tools, but are not designed to handle all the real use cases. Since web pages do not have access to file systems, we can develop these interactions better at the higher level framework.
