### ISSUE TITLE
Thumbnail behavior

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/niivue#474]
After clicking on the thumbnail, the screen with the loading text momentarily popups up before the volumes are shown. I'd expect this screen to be skipped and the volumes to be shown immediately.
Seeing the "waiting for images..." text after clicking on a thumbnail can can be a little confusing. If this waiting-screen is needed, then perhaps a blank screen with no text or a "loading..." text would make more sense in this context.

**Comment by hanayik** [comment]
@AnthonyAndroulakis, the loading text is appearing because the volumes do still need to be loaded. When the thumbnail is shown, any voluming loading is deferred until later. This is so that users can display multiple niivue canvases on a single page without using a lot of memory (loading thumbnails is more efficient than lots of volumes). When the user clicks on the thumbnail, the volumes or meshes are then loaded (see [here](https://github.com/niivue/niivue/blob/main/src/niivue.js#L5318)). 

To achieve the "look" of what you describe above, we could just set the loading text to an empty string. Then it would appear to a user that the images are readily available and will be shown on screen soon after the thumbnail is removed (but not immediately).

**Comment by AnthonyAndroulakis** [comment]
I see. Since this is more about aesthetic preference I can close this issue.
