### ISSUE TITLE
Add Barycentric Effects

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#476]
as mentioned in #458, it would be nice to add these effects since they are implemented in Surfice. If the performance on mobile is likely to be poor, then we can possibly [detect](https://www.tutorialspoint.com/javascript-how-to-detect-if-a-website-is-open-on-a-mobile-or-a-desktop) if running in a mobile browser and disable certain features like this (or at least produce a warning)

**Comment by neurolabusc** [comment]
Closing this issue. Since [issue 482](https://github.com/niivue/niivue/issues/482) we are trying to be mindful of ensuring compatibility and fluid performance for older hardware. While handling barycentric effects is possible, it slightly increases the [per-vertex properties](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html). Furthermore, it prevents efficient [vertex re-use](https://xplanescenery.blogspot.com/2008/11/triangle-optimizations.html). Advanced users can always use Surfice to experience these effects, while the NiiVue [`flat` shader](https://niivue.github.io/niivue/features/meshes.html) provides an efficient way to for users to infer mesh complexity.
