### ISSUE TITLE
是否可以支持vtk文件的渲染

### ISSUE THREAD

**Issue by wujie1314** [niivue/niivue#510]
No examples

**Comment by hanayik** [comment]
@wujie1314 , thanks! Indeed, we seem to have broken our mesh demos due to our recent updates. We will have this fixed soon.

**Comment by wujie1314** [comment]
> @wujie1314 , thanks! Indeed, we seem to have broken our mesh demos due to our recent updates. We will have this fixed soon.

Is the rendering function of vtk files being added?

**Comment by neurolabusc** [comment]
@wujie1314 NiiVue can read [legacy VTK  POLYDATA files described here](http://www.princeton.edu/~efeibush/viscourse/vtk.pdf), we do not support the [VTK XML format](https://kitware.github.io/vtk-examples/site/VTKFileFormats/). We have also tried to support some of the [undocumented features of legacy VTK format](https://discourse.vtk.org/t/upcoming-changes-to-vtkcellarray/2066). Our primary aim was to support the variations popular in our domain: tractography VTK streamlines (saved with either the .vtk or .fib extension) and improve Slicer3D interoperability. The VTK format was really designed to showcase VTK features, and is less well defined than many of the formats we support. 

If you want to test NiiVue's VTK support, open a mesh with [Slicer3D](https://download.slicer.org/) and choose to save it as `Poly Data (.vtk)`. You can then drag and drop this onto NiiVue. Note that NiiVue explicitly **does not** support VTK voxel-based data due to its inability to encode spatial transforms.
![slicer](https://user-images.githubusercontent.com/8930807/219801694-0d266736-35aa-4678-ae61-56e3d96003c1.png)
![niivue](https://user-images.githubusercontent.com/8930807/219801709-a992ddd4-29f8-4906-91ee-446d01a059e7.png)
