### ISSUE TITLE
Rendering of local images issue

### ISSUE THREAD

**Issue by pierre-nedelec** [niivue/niivue#514]
Hello niivue team! Awesome project, thank you for your work! It seems very interesting and I'd love to implement it to view images from a large dataset stored on a cluster, however I'm struggling with a seemingly basic thing. I pulled the example from the README loading the MNI standard volume in html, it works great. Then I downloaded that file and changed the url to the local path, and it didn't work anymore. What am I missing, or is something wrong?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NiiVue</title>
  </head>
  <body>
    <canvas id="gl" width="640" height="640"></canvas>
  </body>
<script src="https://niivue.github.io/niivue/features/niivue.umd.js"></script>
<script>
    var volumeList = [
        {url: "./mni152.nii.gz"}, // ***doesn't work!***
        // {url: "https://niivue.github.io/niivue-demo-images/mni152.nii.gz"}, // works well
    ]
 var nv = new niivue.Niivue({isResizeCanvas: false})
 nv.attachTo('gl') 
 nv.loadVolumes(volumeList)
</script>
</html>
```

**Comment by hanayik** [comment]
@pierre-nedelec , you will need to run a simple web server locally to load images from a URL. 

from the same directory as your html file and the mni152.nii.gz you can do:

## Python3
```bash
python3 -m http.server 8080
```

## Node
```
npx http-server -p 8080
```

**Comment by neurolabusc** [comment]
@pierre-nedelec for security reasons, a web page is forced to live in a sand box: it does not have access to the local file system and faces restrictions with [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). If a user explicitly drags-and-drops a file from the desktop, it is made available to the web page. The `Console` tab of the `Developer Tools` web panel is a great way to see why files are not loaded.

A. For development: You can get access to file from the file system if you run from node, which you can try out in this example: 
```
git clone git@github.com:niivue/niivue.git
cd niivue
npm install
npm run dev
```
B. For web deployment: you will want to view files shared on the web with CORS permissions. An example of this approach is [OpenNeuro](https://openneuro.org/datasets/ds004471/versions/1.0.0/file-display/sub-087:anat:sub-087_run-01_T1w.nii.gz).

C. For desktop applications (e.g. Electron): You will want to use [web sockets or TCP](https://www.scriptol.com/javascript/ipc-vs-websocket.php) so that the application (which can see the users file system) sends messages to the core NiiVue component (which lives in the isolated sandbox). I would recommend TCP, as it does not lock you in to electron (e.g. Tauri, Capacitor,  Proton, etc). For a minimal TCP example, see [niivue-desktop](https://github.com/niivue/niivue-desktop).

D. For iOS applications (e.g. Capacitor.js): You will want to use TCP so that the application (which can see the users file system) sends messages to the core NiiVue component (which lives in the isolated sandbox). For a minimal example, see [niivue-ipad](https://github.com/niivue/niivue-ipad).

**Comment by pierre-nedelec** [comment]
Thank you both for your answer!
@hanayik python answer worked immediately.

Looking into @neurolabusc `npm run dev` view, it's cool to see other examples of what can be done with niivue, it looks super powerful.
