### ISSUE TITLE
render views not interactive via mouse or touch input

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#524]

**Comment by neurolabusc** [comment]
@cdrake this was an unintended consequence of the patch for [issue 518](https://github.com/niivue/niivue/issues/518). Rotating a 3D volume does not change the cross-hair position in image or world space, so we should not generate a location change event. Rather, we generate location change events when a user double-clicks on a volume. Happy to have a Zoom meeting if my patch reintroduces your issue. It is just unclear to me what your issue was and how to replicate it.

**Comment by cdrake** [comment]
Location change event is for the cursor generated by both 2D and 3D views. Bug introduced because I made a mistake in order of assignment.  Will provide fix (with tests) tonight.
