### ISSUE TITLE
Dynamically load color maps or setting minimum display value for noisy data?

### ISSUE THREAD

**Issue by shangjiaxuan** [niivue/niivue#557]
Currently NiiVue can only select from a preset list of color maps. This is enough for most applications, but not seem flexible enough to be general purpose. Consider the following old 3D backscatter imaging data taken years ago with significant noise:
[image.zip](https://github.com/niivue/niivue/files/11110740/image.zip)
Direct load gives the following result:
![fuz](https://user-images.githubusercontent.com/34389517/228818702-1da2be63-9966-42a0-9729-b702c4aaa537.PNG)
![fuz2](https://user-images.githubusercontent.com/34389517/228819348-31d6f0d4-a24d-4c5b-a158-1e0244c8ebb1.PNG)

Whereas in older version MRIcroGL one could adjust transparency and have the following:
![nofuz](https://user-images.githubusercontent.com/34389517/228819717-2f3be6d1-e745-40f4-bd0e-5db3c724ffed.PNG)

Or is there a way to set minimum display value for generic greyscale data?

**Comment by neurolabusc** [comment]
@shangjiaxuan 

 - Your image looks squashed in NiiVue because you have set the `sform_code` to zero, making the spatial transform `unknown`. Therefore, the image orientation and dimensions are ambiguous. When you create a NIfTI image and you want the viewer to use the spatial transformation matrix (the `sform`) make sure you set the `sform_code` to a value of 1 or greater, and make sure this value is **greater** than the `qform_code`. You should set the `qform_code` to zero (`unknown`). See [here](https://brainder.org/2012/09/23/the-nifti-file-format/) for details.

Here are a few ways you can optimize your image that you can explore with the [drawing live demo](https://niivue.github.io/niivue/features/draw.ui.html):
  - Set the minimum and maximum intensity range (cal_min and cal_max) for your image. You can do this via code or by dragging the mouse over a region of the 2D slices that you want to optimize.
  - Choose a colormap that uses hue as well as intensity. Here I have chosen the `Plasma` item from the `Color` menu.
  - Choose `Remove Haze` from the `View` menu to remove noise spikes (using Otsu's method). This works best after you have already set an appropriate intensity range.
 

![blob](https://user-images.githubusercontent.com/8930807/229351026-03b1bccf-ef36-4e2b-b846-c445b03f43a5.png)

**Comment by neurolabusc** [comment]
@shangjiaxuan please see the [colormaps live demo](https://niivue.github.io/niivue/features/colormaps.html) for an example of creating your own custom color tables (the `custom` button).
