### ISSUE TITLE
modulateGlobal parameter?

### ISSUE THREAD

**Issue by mrneont** [niivue/niivue#601]
Howdy-

Is there a parameter/function for setting the global 'opacity' (Alpha value) of an overlayed volume?  That is, currently if I overlay one unthresholded volume B over an underlay A, I can't see anything of A.  The handy `Niivue.prototype.setModulationImage(...)` function allows one to modulate each voxel's Alpha based on a reference volume (great!), but I was wondering if there were a simpler bit of functionality:  putting a max on each voxel's Alpha.  This could be done by:

* defining a new property in `nvimage.js` like:  `this.maxAlpha = 1;`
* defining a function in `niivue.js` like: 
```
Niivue.prototype.setModulationMax = function (
  idTarget,
  maxAlpha = 1
) {
  let idxTarget = this.getVolumeIndexByID(idTarget);
  this.volumes[idxTarget].maxAlpha = maxAlpha;
  this.updateGLVolume();
};
```
* and (after any modulateAlpha considerations have been applied) then checking to see if a volume's `maxAlpha < 1`.  If so, scale the current Alpha value by maxAlpha.  In this way, the global maxAlpha scaling can be applied on top of the modulateAlpha, which is how AFNI applies things, and that has been useful.

Is that reasonable/existing/possible?  I saw this function in niivue.js:
`Niivue.prototype.overlayRGBA = function (volume) {...}`
... but the comments said this was slated for removal.

I would try adding that functionality, but my JS is not so elegant.

thanks,
pt

**Comment by mrneont** [comment]
NB: initially I thought modulateGlobal might be a good name for the described parameter, but then later thought maxAlpha would be (hence the seemingly unrelated Issue title).

**Comment by neurolabusc** [comment]
@mrneont I am not sure I understand the question. You can use the `setOpacity()` function to explicitly set the opacity of an overlay. [Here is a live demo](https://niivue.github.io/niivue/features/atlas.html). Maybe you can be more specific about your use case. Do you think that the volume opacity should be considered when computing the [alpha modulation of one image to the other](https://niivue.github.io/niivue/features/modulateAfni.html)?

**Comment by mrneont** [comment]
Oh, yes, that's it exactly. I guess I had focused on searching for Alpha instead of the obvious...  I'll go get another cup of coffee and hope to be more observant next time.  

Thanks!

**Comment by neurolabusc** [comment]
@mrneont the challenge with multiplying (modulating) a fractional alpha with the already modulated alpha is with generating the outlines. I have created a demo with a possible solution that also shows the limitations. In this example, the `opacity` slider adjusts both the overlay opacity, but also the outline boundary threshold. The issue is that on the GPU we represent the alpha as an 8-bit integer, and we get some slight rounding errors. You can see this in the demo by adjusting the `opacity` slider - note that the outline location wavers a little bit. I think we could add a bit of logic to the alpha modulation formula to fix this, or we could decide the errors are so small that we can ignore them. This approach also reduces the dynamic range of the alpha modulation. Internally, the code introduces a new shader uniform named `overlayOutlineAlpha`. I would consider this feature experimental for now, it seems to have a lot of compromises. There are a couple of ways to achieve this, but they all seem to impact the tidiness and maintainability of the algorithms.

```bash
git clone --branch drawing git@github.com:niivue/niivue.git
cd niivue
npm install
npm run demo
```
And then open the `Modulation of AFNI statistics` demo web page.
![AFNI](https://github.com/niivue/niivue/assets/8930807/37f89042-0971-42a1-b113-e85d86f7bc78)

**Comment by mrneont** [comment]
OK, thanks for looking more into this.  

In the demo on the drawing branch, I only see the Modulation slider, not the additional Opacity one.  But I take the point about the rounding issues here.  Would introducing a flooring() or ceiling() function into the modulation make the truncation errors "consistent", though slightly biased?
