### ISSUE TITLE
Way of telling if .trk file is empty/has no streamlines

### ISSUE THREAD

**Issue by IsaacCrane** [niivue/niivue#607]
In my code, it is possible for a trk file to be used that is empty. When this happens no error occurs but the entire canvas goes blank. Is there a way to have niivue ignore empty files or to see if a file is empty before loading it as a mesh?
Thanks

**Comment by neurolabusc** [comment]
@IsaacCrane can you share an example with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php)? Perhaps you want to add a [head request](https://stackoverflow.com/questions/47536593/any-way-to-get-file-size-from-url-without-downloading-it-using-google-app-script) to detect this. I guess the issue is if this should be handled in NiiVue or in your other code. I am not sure how an empty file should be appropriately interpreted by a viewer as it will not have many of the expected properties.

**Comment by hanayik** [comment]
@IsaacCrane, by empty, do you mean that the file has a size of zero bytes or that the header is intact but with no body?

**Comment by IsaacCrane** [comment]
Here is an example. 
https://fcp-indi.s3.amazonaws.com/data/Projects/HBN/BIDS_curated/derivatives/afq/sub-NDARAC350XUM/ses-HBNsiteCBIC/clean_bundles/sub-NDARAC350XUM_ses-HBNsiteCBIC_acq-64dir_space-T1w_desc-preproc_dwi_space-RASMM_model-CSD_desc-prob-afq-ARC_L_tractography.trk
It has a size of 1 MB and I think it just has no body.

**Comment by neurolabusc** [comment]
@IsaacCrane I am unable to replicate the issue with your 1mb example using [this demo](https://niivue.github.io/niivue/features/tracts2.html) running NiiVue 0.35 - see below.

I note that the [hbn_viewer](https://github.com/nrdg/hbn_viewer) is still running 0.32 (reported by web browser developer tools console). Happy to try again with a 1kb file.

![TRx](https://github.com/niivue/niivue/assets/8930807/44da6163-faad-42c1-8df0-8deaad8e0fee)

**Comment by IsaacCrane** [comment]
Yes. That's my error. 
https://fcp-indi.s3.amazonaws.com/data/Projects/HBN/BIDS_curated/derivatives/afq/sub-NDARAC350XUM/ses-HBNsiteCBIC/clean_bundles/sub-NDARAC350XUM_ses-HBNsiteCBIC_acq-64dir_space-T1w_desc-preproc_dwi_space-RASMM_model-CSD_desc-prob-afq-CGC_L_tractography.trk
This is the one I meant to send. 
Sorry.

**Comment by neurolabusc** [comment]
@IsaacCrane the drawing branch will now fail gracefully if an empty TRK or TRX file is provided. In generally, it might be worth identifying these upstream, as an empty tracts will expose typical properties (opacity color, dither, decimation) even though it will never produce visible streamlines.
