### ISSUE TITLE
create 4D data volume scrolling canvas UI

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#65]
I imagine the canvas UI could look something like this...

![Untitled presentation](https://user-images.githubusercontent.com/5217720/130080760-64ac10d6-097a-498f-87e7-b4cf6d87c7b3.png)

It would be nice to enable picking in the timeline section of the canvas so that a mouse click and drag in that region scrolls through the volumes and re-renders the selected volume in the timeline.

The line plot shows the time series of the voxel under the crosshair. 

The y axis min and max could come from cal_min/max (or global min/max)

**Comment by neurolabusc** [comment]
cal_min and cal_max are probably not good for the y axis. On a typical fMRI scan we expect 2% signal change to be robust, but CSF is dramatically brighter than deep white matter on CSF scans. 

I would work out the minimum and maximum intensity across all plotted values and then choose a suitable `nice number` value for the minimum and maximum. [I reference these notes](https://stackoverflow.com/questions/326679/choosing-an-attractive-linear-scale-for-a-graphs-y-axis) for the MRIcroGL [graphing module](https://github.com/neurolabusc/Metal-Demos/tree/master/graph).

As another much more overacting thought, should each graphical NiiVue instance load independent image data, or should we modularize NiiVue so that multiple instances of NiiVue can share a single NIfTI image. In other words, if you have a graph, render and 2D multiplanar displays on a web page, it might be nice if only a single image was loaded and consuming RAM, shared by separate widgets.

**Comment by neurolabusc** [comment]
Should this be a core function of niivue, or data that is accessible from this component by other tools?

 - [I like these graphs](https://github.com/fordhurley/glsl-grapher)
 - For 3D images, it [may also be useful to show intensity along line](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/tools.html#sample-along-line)

**Comment by neurolabusc** [comment]
If we are going to create graphs for voxel intensity across time, we should also create histograms for intensities within a volume. This is useful for setting image contrast and brightness. To explore this issue, I cloned and then extended the FSLeyes histogram feature.

Here are some observations:

For integer datatypes, it is useful to make adjust the number of bins, such that the integer range is evenly divisible by the number of bins. This reduces aliasing, e.g. here is FSLeyes with a fixed number of bins:
  
![alias](https://user-images.githubusercontent.com/8930807/132342279-360f5046-eb8a-4ee8-b862-3a6eeb8ec98b.png)

It is often useful to allow the user to select a transform. For example, while FSLeyes shows histograms with a linear scale by default, one can [select log scale](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/plot_views.html) to emphasize local maxima and minima. I notice that AFNI visualization uses the Square Root transform for histograms, which tends to work really well. Image below shows the benefit of Square Root (top) over linear (bottom) for fMRI (T2*) data.

![sqrt](https://user-images.githubusercontent.com/8930807/132340746-47aa8c96-f9b3-4793-b1f0-932612297805.png)

**Comment by neurolabusc** [comment]
See the [time series](https://niivue.github.io/niivue/features/timeseries.html) live demo.
