### ISSUE TITLE
I did not find any APIs in the document

### ISSUE THREAD

**Issue by rookiefishs** [niivue/niivue#655]
![image](https://github.com/niivue/niivue/assets/103868319/a65a1348-4ba9-4b1d-b8bd-3b9d54e3940f)

We are a development team from China and currently using niivue as the CT viewing library for the project. However, for some requirements, I cannot find the corresponding API in the document. I hope the niivue development team can help us. I sincerely hope that NIIVUE will become better and better!!! thanks

**Comment by neurolabusc** [comment]
@rookiefishs the default displays of NiiVue are intentionally constrained, so that user experience is consistent across tools (FSL, FreeSurfer, AFNI, nilearn, ezBIDS, OpenNeuro). NiiVue is really focused on the field of neuroimaging, where it is expected that axial slices have Anterior toward the top of the screen. You can choose between radiological and anterior orientation, and whether the sagittal slice is shown with nose left or nose right. Both features are shown in [this live demo](https://niivue.github.io/niivue/features/worldspace.html). NiiVue is open source, so you can make a fork to add the features that are important to you.

Our goal is to create a tool focused on the needs of neuroimaging (visualizing voxels, meshes, connectomes and tractography). If you are looking for a generalized medical imaging voxel viewer you may want to consider [cornerstone.js](https://github.com/cornerstonejs/cornerstone) and its [OHIF viewer](http://viewer.ohif.org/).

I will discuss with other developers if tiles should be centered vertically. I am not partial to one style or the other, but I do think there should be a consistent approach for all our tools, so there would have to be a consensus to change the behavior.

**Comment by rookiefishs** [comment]
Thank you for your answer. The reason our team uses niivue is that it is relatively lightweight and sufficient to meet most of the development needs of the project. However, some details are difficult to debug, and it is also difficult to read the document. If possible, we can add contact information. I have many questions and I am very interested in web digital graphics. Thank you
