### ISSUE TITLE
convert NiiVue to typescript

### ISSUE THREAD

**Issue by cdrake** [niivue/niivue#669]

**Comment by jens-ox** [comment]
I can work on this if it's of interest. I would like to use NiiVue in a TypeScript project, which would require TS declarations to exist. While converting NiiVue to TS isn't required (one could also add declarations to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or add a `types.d.ts` to NiiVue), moving to TS is also beneficial for maintainability and readability in my experience.

**Comment by hanayik** [comment]
@jens-ox , thanks for the offer. We had identified this as a strategic enhancement, but have not devoted any time to it yet. We had been prioritising features first. We meet fortnightly as a group, so perhaps it would be useful to have you attend one of those dev meetings. Let me know. The next one is scheduled for the 29th of Nov at 3pm (uk/london time). If you want to pursue this, then it might be good for you to collaborate with @cdrake since he was going to get to this eventually and might fit into some of his other work to de-monolith `niivue.js` and `nvimage.js`.

**Comment by jens-ox** [comment]
@hanayik thanks for the infos. I will attend the next dev meeting.
@cdrake has there been any work done so far wrt splitting up `niivue.js` and `nvimage.js`? If not, I would recommend starting with the TS migration and doing the split afterwards, as TS will be highly beneficial for that.

**Comment by hanayik** [comment]
closing as done, but see #769
