### ISSUE TITLE
No more than 16 parallel niivue instances?

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#693]
This is a multi-view for comparing many images in the vscode extension. When viewing more than 16 images, only the last 16 are rendered:
<img width="1390" alt="image" src="https://github.com/niivue/niivue/assets/1307522/32703e4e-8cf9-418c-9f4f-c71efffc8718">

It is created with an array of niivue instances linked with sync, and each is drawing in its own canvas
Is this an inherent limit in niivue or maybe webgl?

**Comment by neurolabusc** [comment]
This is an inherent and intentional limitation of WebGL. Note that resources (shader programs, textures) are not shared between WebGL contexts. Each context lives in its own sandbox, which is helpful for security. NiiVue provides very rapid and energy efficient graphics by keeping 3D volumes (textures) in GPU memory (retained mode). However, the tradeoff of this method is that more graphics memory is retained than methods that transfer data between the CPU and GPU for each slice (immediate mode). In theory, one might be able to use the Chrome browser argument [`--max-active-webgl-contexts=<number>`](https://stackoverflow.com/questions/59140439/allowing-more-webgl-contexts), but I think a better approach is to minimize the number of simultaneously active contexts, which will ensure your code works on any device (computer, phone, tablet). Note that you can generate many slices of the same volume in a single WebGL context with the [mosaic](https://niivue.github.io/niivue/features/mosaics2.html) function, but I would limit the number of different contexts (and therefore background images) you display on one web page.

**Comment by korbinian90** [comment]
Thank you for the explanation!
In that case I'm fine with displaying up to 16 volumes
This multi-volume view seems to be an unusual use case. However, it is super convenient for me personally.

**Comment by vincenzoml** [comment]
A workaround seems to be to virtualize the gl context, I believe by rendering to just one context and then copying the buffer back to 2d canvas. An implementation that wraps webgl (I think, making it easy to just plug it into existing code):

https://github.com/greggman/virtual-webgl
