### ISSUE TITLE
GL context lost when creating many viewers

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue#698]
When creating several viewers, I end up with many of them having a sad emoticon in place of the images, because the GL context is lost (a warning is shown in the console). I'm no webgl expert and don't know if there could be methods to mitigate the issue (I've heard of gl context virtualization), or I have to accept that I can't open more than say 10 niivue viewers?

**Comment by vincenzoml** [comment]
This seems an interesting starting point 
https://github.com/greggman/virtual-webgl

**Comment by neurolabusc** [comment]
Please see [issue 693](https://github.com/niivue/niivue/issues/693). This is an intentional limitation of your web browser, not NiiVue.

**Comment by vincenzoml** [comment]
@neurolabusc apart from the virtualization idea, would it be possible to "detach" a niivue object from the canvas, and then reattach it later? So I can just freeze the canvas and unfreeze later when I have more than 16 views open.

**Comment by hanayik** [comment]
Hi @vincenzoml, I'm curious what your use case is. Do you need more than 16 simultaneous webgl contexts or can you create and destroy them as needed? Can you describe how you are using NiiVue within your app?

**Comment by vincenzoml** [comment]
A screenshot is worth a thousand words. I'm writing a dataset-oriented UI to run VoxLogicA(see https://github.com/vincenzoml/VoxLogicA) and neural-networks and visualize the overlays. Indeed I can limit the viewers to 16, and it might even make sense usability-wise, but not sure, because it may be that one wants to open many cases and view the overlays. 

Sure,it's also heavy to load that many viewers in the main thread, but I'm trying to use webworkers for that.

<img width="1275" alt="image" src="https://github.com/niivue/niivue/assets/2283125/9e306473-4845-4d26-bfa5-e781af02ba8a">

**Comment by neurolabusc** [comment]
@vincenzoml the high performance of NiiVue in particular is that it stores the entire 3D volume on the graphics card. For this reason, the data is bound to the context (allowing garbage collection). WebGL and NiiVue are well suited to some problems, but less well suited for others. Perhaps you want to show hundreds of images as static 2D bitmaps using the HTML <img> tag. When the user selects one of these bitmaps, you could load a NiiVue context for interactive manipulation. An extension of this idea is that you have two WebGL contexts: the visible on that the user is interacting with, and a hidden one that asynchronously generates 2D bitmaps for all the other tiles.

**Comment by vincenzoml** [comment]
It may make sense usability-wise to just keep the number of open viewers low, thanks. I will rethink this part of the application.

**Comment by vincenzoml** [comment]
@neurolabusc Suppose I wanted to use a single large viewer, and click on cases to open them inside the viewer. However I also would like to keep the open cases "preloaded": user clicks on case A, case A goes to the viewer, overlays are opened etc. User clicks on case B, the same happens for B. Then user clicks on A again. Now I want A to appear in the state it had before (overlays etc.), and to do that as quickly as possible, ideally instantly.

This could be achieved if the nv object could detach and attach from a canvas (it can attach already, but can it detach? how?). What would be the workflow to achieve the above?

**Comment by neurolabusc** [comment]
My understanding is that browsers limit the number of gl contexts because of all the resources they use. What makes WebGL so fast on mobile devices is that it stores all the data (textures, shaders, buffers, etc) on the GPU. When you detach the context, all of these resources are released.

You could use a single WebGL2 context to [simulate multiple canvases](https://webgl2fundamentals.org/webgl/lessons/webgl-multiple-views.html). This solution outside of the remit of the core NiiVue development team: we already have a very ambitious set of goals so we can not get distracted, and the group tends to prefer a simple API. However, you could always make a fork of NiiVue. However, the NiiVue shaders and buffers are tiny, while typical MRI scans lead to textures that demand a lot of resources. I suspect that loading a large number of 3D volumes onto the GPU will lead to issues for many devices.

You want to choose the tool that is best for your job. WebGL2 has many nice features - thanks to [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) and its shader-based design it is able to leverage the best high performance graphics API for each device (OpenGL, Metal, DirectX, Vulkan).  Therefore, it really does allow you to write one piece of code that provides great graphics on any device. NiiVue leverages its retained mode to provide fast performance and great battery life. However, it is not ideally suited for all jobs. If you want to display a huge number of large 3D textures, using an [immediate mode](https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics)) instead of [retained mode](https://en.wikipedia.org/wiki/Retained_mode) is the appropriate approach.

**Comment by vincenzoml** [comment]
@neurolabusc thanks for the reply; it is now clear to me that it is not a good idea in general to use many viewers because of the textures, makes sense. However my question now stands: using a single viewer/gl canvas, is it possible to quickly switch the nv object attached to it, so that many different cases can be opened, *one at a time*, without destroying the state of the previous viewer? Is it possible to do this in niivue, and if so by which workflow? I imagine there could be something like "save state to memory" and "restore state" but don't understand if it is there among the many methods of the nv object.

**Comment by neurolabusc** [comment]
NiiVue is optimized to work with 3D textures WebGL2 in retained mode. You may want to explore the outstanding [Papaya](https://github.com/rii-mango/Papaya) which uses 2D textures (as WebGL1 does not support 3D textures). I have not looked at the architecture of Papaya, but I would not be surprised if it works in immediate mode.

**Comment by vincenzoml** [comment]
Thanks, I do understand the design of niivue better now, but I have already investigated the alternatives thoroughly and for the moment I'm investing my time and energy in niivue so I want to adapt to the limitations of retained mode in order to take benefit of its advantages.

Perhaps my previous question was not well-thought. What I really need to do, is just serialize the state of the viewer (not the textures) to a variable which is not attached to a canvas, and then later, reattach to the canvas, reload the volumes and finally reload the state (by which I mean position, scaling, current slice type, etc, NOT the textures or the GL data). Is this possible? Easy? Difficult? Requires patching of niivue?

**Comment by hanayik** [comment]
@vincenzoml , you can use the niivue NVDocument format to achieve what you want. There are demos here at the bottom of the page https://niivue.github.io/niivue/. Rather than downloading the saved document, we could return the contents to a variable. The entire state of NiiVue should be preserved. However, it won’t be instant due to serialising and deserialising the image data, but it should be fast enough to offer a pleasant user experience.

**Comment by vincenzoml** [comment]
Very nice. Since I already keep a cache of pre-fetched NVImage objects, would it be faster to avoid serialising the images when serializing, and later re-add the images directly using addVolume (yes I understand this would require patching the source)?

**Comment by vincenzoml** [comment]
The more I work with niivue the more I think providing a fast way to discharge an image to a record of UInt8Arrays and reloading it from there, could be a game changer: one could clone the images and pass them around to web workers, and also save them to indexdb or marshal to localstorage. Based on that, a binary variant of NIIDocument could be provided, that can be in turn cloned to webworkers and saved to indexdb.
