### ISSUE TITLE
nvimage: unclear code

### ISSUE THREAD

**Issue by jens-ox** [niivue/niivue#739]
In [`nvimage.js`](https://github.com/niivue/niivue/blob/main/src/nvimage.js#L1908), some switch statements are a bit hard to understand due to declarations within cases (which are [not lexically scoped](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch#lexical_scoping) and missing break statements.

I don't have enough understanding of the code to raise a PR fixing this, so it would be great if someone more knowledgeable than me could have a look ☺️

**Comment by neurolabusc** [comment]
This function readNRRD() provides a direct mapping from the [NRRD](https://teem.sourceforge.net/nrrd/format.html#spacings) fields to the [NIfTI](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) fields as NiiVue uses NifTI internally for its voxel-based format. Therefore, the line you link to directly maps the NRRD array `spacings[]` to the NIfTI array `pixdim[]`.  Perhaps because I am so familiar with these formats, this seems like the most concise method to convert this format. Please provide guidance to how this can be simplified.

**Comment by jens-ox** [comment]
Hi @neurolabusc! Thanks for the quick reply.

I would change the following:
- add a `break` statement to `case "spacings"`
- scope all declarations in `case "spacings"` and `case "sizes"`
- if it's intentional that `case "spacings"` also executes `case "sizes"`, change the code accordingly

The resulting code would look something like this:

![CleanShot 2023-11-16 at 14 40 26@2x](https://github.com/niivue/niivue/assets/5368029/f07521c5-3cd9-4f58-9ca4-7d57c657bd42)

Assuming that the current behaviour is correct and that `case "sizes"` should indeed run for `spacings`, the code would look like this:

![CleanShot 2023-11-16 at 14 43 04@2x](https://github.com/niivue/niivue/assets/5368029/7c3db32a-142a-4b99-8f58-a25d1567c10f)

**Comment by neurolabusc** [comment]
@jens-ox mea culpa, break added.

**Comment by jens-ox** [comment]
@neurolabusc this will likely still cause issues, as `dims` will not be properly defined.

If it's ok for you I'll raise a PR to introduce some basic linting that chatches stuff like this automatically.
