### ISSUE TITLE
Brainvoyager demo seems to be broken

### ISSUE THREAD

**Issue by jens-ox** [niivue/niivue#768]
While fixing the demos in #757, I noticed that the Brainvoyager demo produces an error.

https://niivue.github.io/niivue/features/brainvoyager.html

```start offset of Float32Array should be a multiple of 4```

**Comment by neurolabusc** [comment]
@hanayik this bug crept in since 0.37.0, presumably when `nvmesh-loaders.js` was created. Can you fix this - the [line](https://github.com/niivue/niivue/blob/f4eb05ac039994697f509d2a89ea11de04c05bae/src/nvmesh-loaders.js#L793)

```
// let filenameSRF = readStr();
```
should be uncommented to read:
```
let filenameSRF = readStr();
```

**Comment by neurolabusc** [comment]
By the way, I think this was commented because the variable `filenameSRF` is not used. However, it is critical to read this variable as this is a variable length null terminated string, so it must be read to determine the offset for subsequent variables. As we improve linting to improve code, we need to define the [preferred method to override line warnings](https://stackoverflow.com/questions/46284405/how-can-i-use-eslint-no-unused-vars-for-a-block-of-code), for example:

```
// eslint-disable-next-line @typescript-eslint/no-unused-vars
```

**Comment by jens-ox** [comment]
@neurolabusc the rule ignores variable names with underscore, e.g. `let _filenameSRF = readStr()` will work.
