### ISSUE TITLE
Type mismatch of mesh id

### ISSUE THREAD

**Issue by korbinian90** [niivue/niivue#844]
The function `setMeshLayerProperty(mesh: number, layer: number, key: keyof NVMeshLayer, val: number)` expects a number as first argument for the mesh identity.

The id of a mesh is a string (from uuidv4())
```
export class NVMesh {
  id: string
```

It seems to still work in the demo (https://niivue.github.io/niivue/features/mesh.4D.html), but confuses the linting.

**Comment by hanayik** [comment]
@korbinian90 , We are working on making the use of `string` IDs and `int` indices more clear. This is part of the documentation PR #890. As you say, the code does still work because of this slightly naughty function that uses `ID` in the name to imply strings, but can also work with number `index` inputs:

```
// not included in public docs
  getMeshIndexByID(id: string | number): number {
    if (typeof id === 'number') {
      if (id >= this.meshes.length) {
        return -1
      } // range 0..len-1
      return id
    }
    const n = this.meshes.length
    for (let i = 0; i < n; i++) {
      const id_i = this.meshes[i].id
      if (id_i === id) {
        return i
      }
    }
    return -1 // -1 signals that no valid index was found for a volume with the given id
  }
```

However, I don't have any linting errors in my vs code, and our linting config isn't highlighting this as an error. Could you share more about your linting config? 

Regardless, this should be made more clear in the upcoming documentation PR (that will include a few code cleanups too).
