### ISSUE TITLE
dist of NiiVue contains incorrect browser polyfills

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#882]
### Context

We are tracing a rare bug where the mere inclusion of NiiVue into a project already using hammer.js and cornerstone-tools breaks cornerstone.

### Bug

The build of `@niivue/niivue` adds polyfills to the `dist/index.js` file. These polyfills are both activated incorrectly and also implemented incorrectly. I have `@niivue/niivue@0.39.0` installed using `npm`. Here are the contents of `node_modules/@niivue/niivue/dist/index.js` lines 17562 to 17567:

```javascript
      if (!Array.forEach) {
        Array.prototype.forEach = function(fn) {
          for (var i2 = 0; i2 < this.length; i2++)
            fn(this[i2], i2, this);
        };
      }
```

1. The expression `!Array.forEach` does not correctly check for whether the polyfill is necessary.

![image](https://github.com/niivue/niivue/assets/20404439/a78151fe-5c5b-4ec5-96d8-67c3232b77d2)

2. The function `Array.prototype.forEach` is 2-arity: the second parameter is an option parameter used as the value for `this`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#thisarg

```javascript
// ECMAScript 2009 class definition
function Foo() {
  this.hello = { value: "hello" }
}

Foo.prototype = {
  printHello: function() {
    console.log(this.hello.value)
  }
}

var foo = new Foo();

[foo].forEach(Foo.prototype.printHello, foo)  // prints "hello"

// poisonous polyfill
Array.prototype.forEach = function(fn) {
  for (var i2 = 0; i2 < this.length; i2++)
    fn(this[i2], i2, this);
};

[foo].forEach(Foo.prototype.printHello, foo)  // Uncaught TypeError: this.hello is undefined
```

**Comment by jennydaman** [comment]
Proposed solution: NiiVue should not be distributed with polyfills. The inclusion of polyfills should be done by the main application.

**Comment by hanayik** [comment]
@jennydaman , yes this does indeed look like an odd bug. I believe once we remove the `noExternal` property from [`tsup.config.ts`](https://github.com/niivue/niivue/blob/7ed03af4163f167ac6a4ef1243538f6b76aa911d/tsup.config.ts#L16) this issue will be resolved. 

Perhaps an intermediate "quick fix" is to have separate tsup configs. One responsible for building a version that supports our tests (simulating using niivue in an end-user application), and another tsup config for building the library so that it can be imported into other projects without errors like this. It also reduces the `dist/index.js` output file from `4.67 MB` to `965 KB`.
