### ISSUE TITLE
saveImage() method should return a uint8Array of the annotated volume  instead, it's returning the uint8Array of the original volume 

### ISSUE THREAD

**Issue by anjugajbhiye91** [niivue/niivue#891]
In latest version "@niivue/niivue": "^0.39.0", saveImage() method supposed to return a uint8Array of the annotated volume , but instead, it's returning the uint8Array of the original volume on which the annotation was drawn.

In earlier version "@niivue/niivue": "0.38.10",  saveImage() method was downloading the annoted volume niftii.

So i am expecting the annoted volume niftii uint8array to be retrun by saveImage().

My expected output is when I draw/annotate on volume I want the uintarray of annoted volume not the. original volume on which the annotation was drawn,   

    let fnm = "tumor_" + this.data.patient + "_" + new Date().getTime() + ".nii.gz";
    let saveData = this.nv.saveImage(fnm, true);
    const myFile = new File([saveData.buffer], fnm, {
      type: 'application/gzip',
    });
    const formData = new FormData();
    formData.append("file", myFile);

above sample code for reference to handle the response of saveImage(). Please guide me and let me know anything wrong in the code

**Comment by neurolabusc** [comment]
@anjugajbhiye91 you will want to look at the [saveImage()](https://niivue.github.io/niivue/devdocs/classes/Niivue.html#saveImage) documentation. With the move to TypeScript, the options are all stored in a structure. If you want to save the drawing rather than the background image, you will want to set the `isSaveDrawing` to true:

```
niivue.saveImage({ filename: "myimage.nii.gz", isSaveDrawing: true });
```
You may also want to look at the [source code](https://github.com/niivue/niivue/blob/bef7941124538e3e593fbce632b7d67826c9bc1e/src/niivue/index.ts#L362C6-L362C22):
```
type SaveImageOptions = {
  filename: string
  isSaveDrawing: boolean
  volumeByIndex: number
}
```

**Comment by hanayik** [comment]
I agree with @neurolabusc. The saveImage function is working correctly when the inputs are supplied as an object. Closing, this issue,  but reopen if needed. 

Also, while Niivue is below version 1.0.0 there may be slight API changes from time to time as we finalise the interface. This was one of those small changes.
