### ISSUE TITLE
add type annotation to onLocationChange

### ISSUE THREAD

**Issue by hanayik** [niivue/niivue#963]

**Comment by thangngoc89** [comment]
This is from my project's code snippet. You can use it as a starting point. Public domain license.

```
type NiiVueLocationValue = {
  id: string;
  mm: Float32Array;
  name: string;
  value: number;
  vox: [number, number, number];
};
```

**Comment by neurolabusc** [comment]
@thangngoc89 this is a good start. Here is a screenshot of the structure:

 
<img width="646" alt="Screenshot 2024-05-06 at 6 04 00 AM" src="https://github.com/niivue/niivue/assets/8930807/e60e7364-227b-494b-9c99-a11f296d8319">

Therefore, I think the full description is:
```
type NiiVueLocationValue = {
  id: string;
  mm: Float32Array;
  name: string;
  value: number;
  vox: [number, number, number];
};
type NiiVueLocation = {
  axcorsag: number;
  frac: Float32Array;
  mm: Float32Array;
  string: string;
  values: NiiVueLocationValue[];
  vox: Float32Array;
  xy: [number, number];
};
```
At first inspection, the fact that `vox` and `mm` are reported for both the main structure and separately for each layer. However, it is worth noting that all overlays are resliced to match the resolution and field-of-view of the background image. Therefore, due to interpolation, rotation and zoom, the overlays are often different from the background image.
