### ISSUE TITLE
Posterior on the right for radiological convention 

### ISSUE THREAD

**Issue by jennydaman** [niivue/niivue#991]
Hello, we have a feature request (or request for guidance): currently, the `isRadiologicalConvention` setting flips coronal and axial views. However, one of our neuroradiologists have noted that the sagittal image needs to be flipped as well, so that posterior is on the right.

Can a setting be created for this? Alternatively, can this be achieved w/o modifying niivue?

**Comment by neurolabusc** [comment]
This is the expected behavior. The setRadiologicalConvention() sets radiological vs neurological convention which influences the coronal and axial view. The opts.sagittalNoseLeft sets the orientation of the anterior-posterior dimension on the sagittal view. Checkboxes in the [advanced mosaic live demo](https://niivue.github.io/niivue/features/mosaics2.html) shows how you can indpedently control these:

```
nv1.setRadiologicalConvention(this.checked)
nv1.opts.sagittalNoseLeft = this.checked
```

For completeness, [radiological and neurological convention influences 2D slices](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Neurological_versus_radiological_convention) but does not influence volume rendering where depth is explicit. For most volume rendering, the azimuth and elevation of the camera set the depth. However, for the mosaic renderings it is the polarity of the number that influences this.  This is illustrated in the [basic mosaic live demo](https://niivue.github.io/niivue/features/mosaics.html), where you can dynamically set the mosaic string to `R X 0` versus `R X -0`.

**Comment by jennydaman** [comment]
`nv1.opts.sagittalNoseLeft` is what I am looking for, thanks!

**Comment by neurolabusc** [comment]
Great. It is worth noting that nose left/right convention is independent radiological/neurological convention. NiiVue is designed for compatibility with FreeSurfer, FSLeyes, and MRIcroGL all of which provide neurological/radiological options that do not influence the sagittal view.
