### ISSUE TITLE
Slow 3D performance when Chrome dev tools are open

### ISSUE THREAD

**Issue by hsellik** [niivue/niivue#998]
Hi

When trying out the anti-aliasing demo, I noticed that the performance of the 3D render drops significantly when the dev console is open on large resolution screens.

Steps to reproduce:
* Use a large resolution monitor
* Open https://niivue.github.io/niivue/features/vox.aaON.html 
* Open developer console
* See if the 3D is slow
  * If not, try refeshing with the dev console open
* The 3D should be slow when trying to mo 

Tried out with 2 different macs on 2 different monitors.

## System Info
```
Monitor resolution:
    3840x2160
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 91.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
```

Otherwise, NiiVue is quite awesome and the 3D rendering is very performant.

**Comment by neurolabusc** [comment]
This is the expected behavior. The purpose of the [Anti-Aliasing on](https://niivue.github.io/niivue/features/vox.aaON.html) and [Anti-Aliasing off](https://niivue.github.io/niivue/features/vox.aaOFF.html) live demos is to demonstrate how [anti-aliasing](https://medium.com/@pixelscommander/why-does-webgl-antialiasing-lie-51e5d3e208bb) and [high-DPI](https://www.khronos.org/webgl/wiki/HandlingHighDPI) (aka `retina`) screens trade off quality for speed. This effect can be compounded by the developer console (though that impacts developers more than end users).

In general, volume rendering is computationally expensive - in these live demos you can see how choosing the 2D (axial, coronal or sagittal) view improves performance. 

We have tried to make NiiVue run  quickly on low power devices (phones, tablets, laptops) and conserve battery life (e.g. unlike many WebGL engines, the scene is only refreshed when it changes, not automatically at ~60 fps). However, we do also allow developers to make their own choices in the quality and performance tradeoff. 

It is unfortunate that most web browsers restrict access to information about the users graphics card (for privacy against malicious web page creators). Therefore, it is hard to come up with a perfect strategy of automatically providing the best performance.

The M1 is an outstanding GPU for its time, die size and power constraints. Indeed, all the NiiVue graphics were developed on one. However, you must be realistic about your expectactions. It provides about [2.6 TFLOPs](https://en.wikipedia.org/wiki/Apple_M1) while a M3 Max provides [14.2 TFLOPs](https://www.cpu-monkey.com/en/igpu-apple_m3_max_40_core). A challenge when creating graphics tools is to support users in under-resourced environments while providing the best performance. 

As an aside, the other considerations for NiiVue speed/quality tradeoff are:
 - [Mesh XRay](https://niivue.github.io/niivue/features/tracts2.html)
 - [non-Matte volume rendering](https://niivue.github.io/niivue/features/shiny.volumes.html) is slower than matte volume rendering, with the `slices` volume rendering mode the fastest.
 - [Extremely complex](https://nrdg.github.io/tractoscope/) meshes and streamlines. In particular, streamlines are much slower with non-zero [radius](https://niivue.github.io/niivue/features/tracts2.html) (cylinders) than single-pixel lines.
